"""
Run: python3 hello_bfs_08_queue_state.py

Recap: step 4 tacked a distance onto each queue entry; step 7 seeded
several entries at once.

Step 8: state in the queue — a queue entry can carry whatever a
problem needs, not just a position and a distance. Word Ladder's queue
holds `(word, steps)`; Open the Lock's holds `(combination, turns)`;
Perfect Squares' holds `(remainder, steps)`. The "neighbors" of an
entry are then generated by a rule specific to that state, not a fixed
grid offset or a stored adjacency list.

The mental model: before writing the loop, ask "what does one queue
entry need to fully describe where I am?" — that answer becomes the
tuple you push, and "generate neighbors" becomes "apply every valid
transformation to this state."

Speedrun:
  - bfs/problems/medium_994_rotting-oranges.py
  - bfs/problems/medium_1091_shortest-path-in-binary-matrix.py
  - bfs/problems/medium_1926_nearest-exit-from-entrance-in-maze.py
  - bfs/problems/hard_127_word-ladder.py
  - bfs/problems/medium_752_open-the-lock.py
  - bfs/problems/medium_279_perfect-squares.py
  - bfs/problems/medium_934_shortest-bridge.py
"""
from collections import deque


def num_squares(n: int) -> int:
    squares = []
    i = 1
    while i * i <= n:
        squares.append(i * i)
        i += 1

    visited = {n}
    queue = deque([(n, 0)])   # state = (remainder, steps), not a bare position
    while queue:
        remainder, steps = queue.popleft()
        if remainder == 0:
            return steps
        for square in squares:
            if square > remainder:
                break
            next_remainder = remainder - square   # "neighbor" = subtract one square
            if next_remainder not in visited:
                visited.add(next_remainder)
                queue.append((next_remainder, steps + 1))
    return -1


def test_num_squares():
    assert num_squares(12) == 3
    assert num_squares(13) == 2


if __name__ == "__main__":
    test_num_squares()
    print("OK")
